// test that try runs both block and finally clause
{
    try {
        try {
            log "body";
            throw new Exception();
            log "throw failed";
        } finally {
            log "finally";
        }
    } catch( Exception ex ) {
    }
}
